[package]
name = "pix2wav"
version = "0.1.0"
authors = ["Alberto López <alberto.lopez@jediupc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
itertools = "0.10.0"